package com.aegis.agents

import com.aegis.ai.InferenceEngine
import com.aegis.core.*
import com.aegis.data.repository.GuardianMemoryRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class DeepfakeAgent(
    private val inferenceEngine: InferenceEngine? = null
) : GuardianAgent {

    override val name = "DeepfakeAgent"
    override val version = "1.0.0"
    override val description = "Detects AI-generated synthetic media, deepfakes, and manipulated content"

    private val deepfakeIndicators = listOf(
        "ai generated", "synthetic", "deepfake", "face swap", "voice clone",
        "artificial intelligence", "machine learning generated", "neural network",
        "computer generated", "digital manipulation", "synthetic media"
    )

    private val suspiciousPatterns = listOf(
        Regex("""(?i)(unrealistic|unnatural|glitchy|blurry|inconsistent).*face"""),
        Regex("""(?i)(lip sync|audio mismatch|voice doesn't match)"""),
        Regex("""(?i)(too perfect|uncanny valley|robotic)"""),
        Regex("""(?i)(generated by|created with|using ai|powered by)""")
    )

    override suspend fun analyze(
        context: AnalysisContext,
        memory: GuardianMemoryRepository?,
        previousResults: List<AgentResult>
    ): AgentResult =
        withContext(Dispatchers.Default) {
            val text = context.text ?: return@withContext safeResult
            val imageUrl = context.url
            val hasImage = context.metadata.containsKey("has_image") && context.metadata["has_image"] == "true"
            val hasAudio = context.metadata.containsKey("has_audio") && context.metadata["has_audio"] == "true"

            val textScore = analyzeText(text)
            val mediaScore = if (hasImage || hasAudio) {
                analyzeMedia(context, hasImage, hasAudio)
            } else 0f

            val mlScore = inferenceEngine?.classify(text, "deepfake_detection", context.metadata) ?: 0f

            // Weighted combination: Text (30%), Media (40%), ML (30%)
            val combinedScore = (textScore * 0.3f + mediaScore * 0.4f + mlScore * 0.3f).coerceIn(0f, 1f)
            val threatLevel = scoreToThreatLevel(combinedScore)

            val reason = buildReason(threatLevel, combinedScore, hasImage, hasAudio)
            val details = buildDetails(textScore, mediaScore, mlScore, hasImage, hasAudio)

            AgentResult(
                agentName = name,
                threatLevel = threatLevel,
                confidence = combinedScore,
                reason = reason,
                details = details,
                suggestedAction = getSuggestedAction(threatLevel, hasImage, hasAudio),
                requiresUserAttention = threatLevel.value >= ThreatLevel.MALICIOUS.value
            )
        }

    private fun analyzeText(text: String): Float {
        var score = 0f
        val textLower = text.lowercase()

        val indicatorMatches = deepfakeIndicators.count { textLower.contains(it) }
        score += indicatorMatches * 0.15f

        val patternMatches = suspiciousPatterns.count { it.containsMatchIn(text) }
        score += patternMatches * 0.2f

        // Check for claims of authenticity (often used in deepfakes)
        if (textLower.contains("real") && textLower.contains("video")) score += 0.1f
        if (textLower.contains("not fake") || textLower.contains("genuine")) score += 0.1f

        return score.coerceIn(0f, 1f)
    }

    private fun analyzeMedia(context: AnalysisContext, hasImage: Boolean, hasAudio: Boolean): Float {
        var score = 0f

        // If media is present, increase base suspicion score
        if (hasImage) score += 0.3f
        if (hasAudio) score += 0.2f

        // Check metadata for manipulation signs
        val metadata = context.metadata
        if (metadata["editing_software"] != null) score += 0.3f
        if (metadata["compression_artifacts"] == "high") score += 0.2f

        return score.coerceIn(0f, 1f)
    }

    private fun scoreToThreatLevel(score: Float): ThreatLevel = when {
        score >= 0.7f -> ThreatLevel.CRITICAL
        score >= 0.5f -> ThreatLevel.MALICIOUS
        score >= 0.3f -> ThreatLevel.LIKELY_MALICIOUS
        score >= 0.15f -> ThreatLevel.SUSPICIOUS
        else -> ThreatLevel.SAFE
    }

    private fun buildReason(level: ThreatLevel, score: Float, hasImage: Boolean, hasAudio: Boolean): String {
        val mediaContext = when {
            hasImage && hasAudio -> "in video/audio content"
            hasImage -> "in image content"
            hasAudio -> "in audio content"
            else -> "in text content"
        }

        return when (level) {
            ThreatLevel.SAFE -> "No deepfake indicators detected"
            ThreatLevel.SUSPICIOUS -> "Potential synthetic content markers found $mediaContext (${(score * 100).toInt()}% confidence)"
            ThreatLevel.LIKELY_MALICIOUS -> "Multiple deepfake indicators detected $mediaContext"
            ThreatLevel.MALICIOUS -> "Strong evidence of AI-generated or manipulated content"
            ThreatLevel.CRITICAL -> "Critical deepfake threat detected - content likely synthetic"
        }
    }

    private fun buildDetails(textScore: Float, mediaScore: Float, mlScore: Float, hasImage: Boolean, hasAudio: Boolean): Map<String, String> {
        return mapOf(
            "text_score" to textScore.toString(),
            "media_score" to mediaScore.toString(),
            "ml_score" to mlScore.toString(),
            "has_image" to hasImage.toString(),
            "has_audio" to hasAudio.toString(),
            "content_type" to when {
                hasImage && hasAudio -> "video"
                hasImage -> "image"
                hasAudio -> "audio"
                else -> "text"
            }
        )
    }

    private fun getSuggestedAction(level: ThreatLevel, hasImage: Boolean, hasAudio: Boolean): String? {
        return when (level) {
            ThreatLevel.SAFE -> null
            ThreatLevel.SUSPICIOUS -> "Verify the source and authenticity of this content before sharing."
            ThreatLevel.LIKELY_MALICIOUS -> "This content may be AI-generated. Do not share or act on it without verification."
            ThreatLevel.MALICIOUS -> "Likely synthetic content detected. Report and do not distribute."
            ThreatLevel.CRITICAL -> "Critical: This appears to be a deepfake. Block source and report immediately."
        }
    }

    private val safeResult get() = AgentResult(
        agentName = name,
        threatLevel = ThreatLevel.SAFE,
        confidence = 0f,
        reason = "No content to analyze"
    )
}
